"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Mail } from "lucide-react";
import { GithubIcon, LinkedinIcon } from "./icons";

const ROLES = ["frontend-heavy fullstack developer", "clean, typed API builder", "scalable web solution shipper", "ships real products, not just demos"];
const STATIC_LINES = [{ prompt: "$ whoami", output: "ravhi" }, { prompt: "$ cat shipping.txt", output: "captionin.varstory.my.id — live in production" }];
const INTRO_LINES = [STATIC_LINES[0], { prompt: "$ cat role.txt", output: ROLES[0] }, STATIC_LINES[1]];

export default function Hero() {
  const [introDone, setIntroDone] = useState(false); const [visibleLines, setVisibleLines] = useState(0); const [typedOutput, setTypedOutput] = useState(""); const [roleText, setRoleText] = useState(ROLES[0]);
  useEffect(() => { if (visibleLines >= INTRO_LINES.length) return; const current = INTRO_LINES[visibleLines].output; let i = 0; const typing = setInterval(() => { i++; setTypedOutput(current.slice(0, i)); if (i >= current.length) { clearInterval(typing); setTimeout(() => { setVisibleLines((v) => v + 1); setTypedOutput(""); if (visibleLines === INTRO_LINES.length - 1) setIntroDone(true); }, 280); } }, 22); return () => clearInterval(typing); }, [visibleLines]);
  useEffect(() => { if (!introDone) return; let index = 0, charIndex = ROLES[0].length; let phase: "hold" | "deleting" | "typing" = "hold"; let timeout: ReturnType<typeof setTimeout>; const tick = () => { const word = ROLES[index]; if (phase === "hold") { timeout = setTimeout(() => { phase = "deleting"; tick(); }, 1800); return; } if (phase === "deleting") { charIndex--; setRoleText(word.slice(0, charIndex)); if (charIndex <= 0) { index = (index + 1) % ROLES.length; phase = "typing"; } timeout = setTimeout(tick, 22); return; } charIndex++; setRoleText(ROLES[index].slice(0, charIndex)); if (charIndex >= ROLES[index].length) phase = "hold"; timeout = setTimeout(tick, 32); }; tick(); return () => clearTimeout(timeout); }, [introDone]);
  return <section id="hero" className="section-shell flex min-h-[92vh] flex-col justify-center gap-12 py-24 lg:flex-row lg:items-center lg:gap-20">
    <div className="flex-1"><div className="mb-7 flex items-center gap-3"><span className="size-2 rounded-full bg-primary shadow-[0_0_14px_var(--accent)]" /><span className="section-kicker">Available for opportunities · Jakarta / Remote</span></div><h1 className="display-type max-w-4xl text-6xl font-bold leading-[.9] sm:text-8xl">Building digital<br /><span className="text-primary">things that matter.</span></h1><p className="mt-8 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">Saya Ravhi, developer yang suka mengubah problem rumit menjadi produk web yang cepat, terukur, dan enak dipakai.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#featured" className="group inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5">See selected work <ArrowDownRight className="transition-transform group-hover:translate-x-1 group-hover:translate-y-1" /></a><a href="mailto:ravhi.wibowo97@gmail.com" className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-sm text-foreground transition-colors hover:border-primary"><Mail data-icon="inline-start" /> Let&apos;s talk</a></div><div className="mt-12 flex gap-8 border-t border-border pt-5"><div><p className="font-mono text-2xl font-bold text-foreground">01</p><p className="text-xs text-muted-foreground">product in production</p></div><div><p className="font-mono text-2xl font-bold text-foreground">3+</p><p className="text-xs text-muted-foreground">years building things</p></div><div className="flex items-center gap-3"><a aria-label="GitHub" href="https://github.com/ravhihz" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary"><GithubIcon /></a><a aria-label="LinkedIn" href="https://www.linkedin.com/in/ravhihariswibowo" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary"><LinkedinIcon /></a></div></div></div>
    <div className="w-full max-w-md rotate-1 rounded-2xl border border-border bg-card p-2 shadow-2xl shadow-black/40 lg:rotate-2"><div className="rounded-xl border border-border bg-background"><div className="flex items-center justify-between border-b border-border px-4 py-3"><span className="font-mono text-xs text-muted-foreground">ravhi@portfolio ~</span><span className="font-mono text-[10px] text-primary">LIVE</span></div><div className="min-h-64 p-5 font-mono text-xs leading-7 sm:text-sm">{!introDone ? <>{INTRO_LINES.slice(0, visibleLines).map((line, idx) => <div key={idx} className="mb-3"><p className="text-primary">{line.prompt}</p><p className="text-foreground">{line.output}</p></div>)}{visibleLines < INTRO_LINES.length && <div><p className="text-primary">{INTRO_LINES[visibleLines].prompt}</p><p className="text-foreground">{typedOutput}<span className="animate-pulse">▋</span></p></div>}</> : <><p className="text-primary">$ whoami</p><p className="mb-3 text-foreground">ravhi</p><p className="text-primary">$ cat role.txt</p><p className="mb-3 text-foreground">{roleText}<span className="animate-pulse">▋</span></p><p className="text-primary">$ cat shipping.txt</p><p className="text-foreground">captionin.varstory.my.id</p></>}</div></div><div className="flex items-center justify-between px-4 py-3 font-mono text-[10px] text-muted-foreground"><span>01 / 08 sections</span><ArrowUpRight className="size-4 text-primary" /></div></div>
  </section>;
}
